id: appspec-yml-disclosure

info:
  name: Appspec Yml Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json
  tags: exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/appspec.yml"
      - "{{BaseURL}}/appspec.yaml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "version:"
          - "os:"
          - "files:"
        part: body
        condition: and

      - type: status
        status:
          - 200
