id: awstats-script

info:
  name: AWStats script
  author: sheikhrishad
  severity: info
  tags: config,exposure,awstats

requests:
  - method: GET
    path:
      - "{{BaseURL}}/awstats.pl"
      - "{{BaseURL}}/logs/awstats.pl"
      - "{{BaseURL}}/webstats/awstats.pl"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Do not remove this line"

      - type: word
        part: header
        words:
          - "application/x-perl"

      - type: status
        status:
          - 200