id: hp-ilo-serial-key-disclosure

info:
  name: HP ILO Serial Key Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/hp-ilo-serial-key-disclosure.json
  tags: exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/xmldata?item=CpqKey"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "LTYPE"
          - "LNAME"
          - "KEY"
        part: body
        condition: and

      - type: status
        status:
          - 200
