id: jetbrains-datasource

info:
  name: Jetbrains IDE DataSources exposure
  author: FlorianMaak
  severity: info
  description: Contains uuid of datasource to retrieve via .idea/dataSources/{uuid}.xml to expose database structure.
  tags: config,exposure,jetbrains

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.idea/dataSources.xml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DataSourceManagerImpl"
        part: body

      - type: status
        status:
          - 200
