id: netbeans-config

info:
  name: Exposed Netbeans configuration
  author: sbani
  severity: info
  description: Searches for a exposed Netbeans configuration
  tags: netbeans,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/nbproject/project.properties"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(?mi)^src.dir="
          - "(?mi)^build.[a-zA-Z]+="
          - "(?mi)^jar.[a-zA-Z]+="
        condition: or

      - type: status
        status:
          - 200
