id: phalcon-framework-source

info:
  name: Phalcon Framework Source Code leakage
  author: philippedelteil
  severity: high
  tags: exposure,debug,phalcon

requests:
  - method: GET
    path:
      - "{{BaseURL}}/anything_here"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Phalcon Framework"
          - "AnythingHereController"
        condition: and

      - type: status
        status:
          - 200