id: tugboat-config-exposure

info:
  name: Tugboat configuration file exposure
  description: Tugboat is a command line tool for interacting with your DigitalOcean droplets.
  reference: https://github.com/petems/tugboat
  author: geeknik
  severity: critical
  tags: tugboat,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.tugboat"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "authentication"
          - "access_token"
          - "ssh_user"
        condition: and

    extractors:
      - type: regex
        part: body
        regex:
          - 'access_token: .*'
