id: kubernetes-enterprise-manager

info:
  name: Detect Kubernetes Enterprise Manager
  author: pussycat0x
  severity: info
  tags: tech,kubernetes
  metadata:
    fofa-query: 'app="Kubernetes-Enterprise-Manager"'

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Kubernetes Enterprise Manager"

      - type: status
        status:
          - 200
